apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  # The project is correct, as it grants the necessary cluster-wide permissions.
  project: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      releaseName: ingress-nginx
      # UPDATED SECTION:
      # These values help avoid the hook deadlock.
      values: |
        controller:
          admissionWebhooks:
            failurePolicy: Ignore
            annotations:      # Add this block
              argocd.argoproj.io/hook: PostSync
              argocd.argoproj.io/hook-delete-policy: HookSucceeded
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # UPDATED SECTION:
    # Adding ServerSideApply and Replace helps Argo CD better handle the complex
    # dependencies within the ingress-nginx chart.
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - Wait=true  # Ensures Argo CD waits for the resources to be ready before marking sync as complete
