applications:
  - name: ${app_name}
    project: default
    source:
      repoURL: ${repo_url}
      targetRevision: HEAD
      path: ${repo_path}
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated: {}
      syncOptions:
        - CreateNamespace=true
server:
  service:
    type: LoadBalancer
