provider: 
  name: cloudflare
policy: sync
# Provide the Cloudflare API token securely using Kubernetes secrets
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiKey