# This manifest defines two ClusterIssuers for cert-manager:
# one for Let's Encrypt staging (for testing) and one for production.
# ClusterIssuer for Let's Encrypt staging environment.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Email address for Let's Encrypt account notifications.
    # You must replace this with your own email address.
    email: lukas.zainzinger@gmail.com
    # ACME server URL for certificate requests.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Secret to store the ACME account's private key.
    privateKeySecretRef:
      # This secret will be created automatically by cert-manager to store
      # the ACME account's private key.
      name: letsencrypt-staging-key
    # Define how cert-manager should solve ACME challenges (HTTP-01 via ingress-nginx).
    solvers:
    - http01:
        ingress:
          class: nginx
---
# ClusterIssuer for Let's Encrypt production environment.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Email address for Let's Encrypt account notifications.
    email: lukas.zainzinger@gmail.com
    # ACME server URL for certificate requests.
    server: https://acme-v02.api.letsencrypt.org/directory
    # Secret to store the ACME account's private key.
    privateKeySecretRef:
      # A different secret for the production account key.
      name: letsencrypt-prod-key
    # Define how cert-manager should solve ACME challenges (HTTP-01 via ingress-nginx).
    solvers:
    - http01:
        ingress:
          class: nginx