apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webshop-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  generators:
    - git:
      repoURL: https://github.com/MCCE2024/INENPT-G8.git
      revision: feature/argo-cd-setup
      files:
      - path: "gitops-base/apps/webshop/tenants/*/values.yaml"
  template:
    metadata:
      name: "webshop-{{path.basename}}"
    spec:
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PrunePropagationPolicy=foreground
        - PrunePropagationPolicy=background
        - CreateNamespace=true
        - ServerSideApply=true
      sources:
        - path: Charts/webshop
          repoURL: https://github.com/MCCE2024/AKTT1_G8.git
          targetRevision: 1.3.0
          helm:
            valueFiles:
            - $values/gitops-base/apps/webshop/tenants/{{path.basename}}/values.yaml
        - repoURL: https://github.com/MCCE2024/INENPT-G8.git
          targetRevision: feature/argo-cd-setup
          ref: values
      destination:
        namespace: '{{path.basename}}'
        server: "https://kubernetes.default.svc"