apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webshop-applicationset
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MCCE2024/INENPT-G8.git
      revision: feature/argo-cd-setup
      files:
      - path: "gitops-base/apps/webshop/tenants/*/values.yaml"
  template:
    metadata:
      name: 'webshop-{{path.basename}}'
      labels:
        tenant: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/MCCE2024/AKTT1_G8.git
        targetRevision: HEAD
        path: Chart/webshop
        helm:
          valueFiles:
          - $values/apps/webshop/tenants/{{path.basename}}/values.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: 'webshop-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true