apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webshop-matrix
spec:
  generators:
    - matrix:
        generators:
          # Tenant values generator
          - git:
              repoURL: https://github.com/MCCE2024/INENPT-G8
              revision: feature/argo-cd-setup
              directories:
                - path: "gitops-base/apps/webshop/tenants/*"
          
          # Helm chart generator 
          - git:
              repoURL: https://github.com/MCCE2024/AKTT1_G8
              revision: 1.3.0
              files:
                - path: "Chart/webshop/**"

  template:
    metadata:
      name: "webshop-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/MCCE2024/AKTT1_G8
        targetRevision: 1.3.0
        path: "Charts/webshop"
        helm:
          valueFiles:
            - "../../../../INENPT-G8/gitops-base/apps/webshop/tenants/{{path.basename}}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
