apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: webshop-applicationset
  namespace: argocd
spec:
  # (1) THE GENERATOR: Find all .yaml files in the 'environments' directory.
  generators:
    - git:
        # The repo where the values files are.
        repoURL: https://github.com/MCCE2024/INENPT-G8.git
        revision: feature/argo-cd-setup
        directories:
          # The glob pattern to find the files.
          - path: "gitops-base/apps/webshop/tenants/*"

  # (2) THE TEMPLATE: This is the blueprint for the Applications that will be created.
  template:
    metadata:
      # Create a unique name for each app based on the filename (e.g., 'my-awesome-app-staging')
      name: 'webshop-{{path.basename}}'
    spec:
      project: default
      
      # (3) SOURCE: Defines the Helm chart and which values file to use.
      source:
        # The repo where the Helm chart is.
        # The Git repository where the chart source is
        repoURL: https://github.com/MCCE2024/AKTT1_G8.git

        # The branch or tag in the Git repo to use
        targetRevision: 1.3.0

        # The path to the directory containing Chart.yaml inside the Git repo
        path: Charts/webshop # <-- Use 'path' instead of 'chart'
        
        helm:
          # (4) THE MAGIC LINK: This placeholder tells Argo CD to use the
          # values file that was found by the generator for this specific application.
          # values.yaml in directory 'tenants'
          valueFiles:
            - '{{path.basename}}/values.yaml'  # Use the basename of the directory as the values file

      # DESTINATION: Where to deploy the application.
      destination:
        server: https://kubernetes.default.svc
        # You can also parameterize the namespace if needed, e.g.:
        # namespace: 'my-app-{{path.basenameNormalized}}'
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true