apiVersion: argoproj.io/v1alpha1  # API version of the Argo CD Application resource
kind: Application  # Kind of Kubernetes resource, here it is an Argo CD Application
metadata:
  name: podtato-head-2  # Name of the Argo CD Application
  namespace: argocd  # Namespace where the Argo CD Application is deployed
spec:
  project: default  # Argo CD project this application belongs to
  source:
    repoURL: https://github.com/podtato-head/podtato-head-app.git  # Git repository URL containing the application manifests or Helm chart
    targetRevision: v0.3.0  # Git revision (branch, tag or commit) to sync from
    path: chart  # Path within the repository where the application manifests or Helm chart are located
  destination:
    server: https://kubernetes.default.svc  # Kubernetes API server URL where the app will be deployed (in-cluster)
    namespace: podtato-helm  # Kubernetes namespace where the application resources will be created
  syncPolicy:
    automated:  # Enables automated syncing of the application
      selfHeal: true  # Automatically revert changes made to the live cluster that diverge from the desired state
      prune: true  # Automatically delete resources that are no longer defined in the source repository
    syncOptions:
      - CreateNamespace=true  # Automatically create the destination namespace if it does not exist