name: Terraform Plan & Apply  # Name of the workflow

on:
  pull_request:              # Trigger on PRs targeting main
    branches: [ main ]
  push:                      # Trigger on commits pushed to main
    branches: [ main ]

jobs:
  terraform:                 # Define a job called 'terraform'
    runs-on: ubuntu-latest   # Use latest Ubuntu runner

    env:                     # Define environment variables from GitHub secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
      EXOSCALE_REGION: "at-vie-2"

    steps:
      - name: Checkout repository  # Step 1: Checkout code
        uses: actions/checkout@v4

      - name: Install Exoscale CLI
        continue-on-error: true
        run: |
          curl -fsSL https://raw.githubusercontent.com/exoscale/cli/master/install-latest.sh | sh

      - name: Fetch SKS kubeconfig and store
        continue-on-error: true
        run: |
          CLUSTER_NAME=$(exo compute sks list --zone at-vie-2 --output-format json | jq -r '.[0].name')
          exo compute sks kubeconfig $CLUSTER_NAME admin --zone at-vie-2 > kubeconfig
          chmod 600 kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      - name: Validate Kubernetes access
        continue-on-error: true
        run: |
          kubectl get nodes

      - name: Install OpenTofu     # Step 2: Install OpenTofu CLI
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0 

      - name: Initialize OpenTofu  # Step 3: Initialize the working directory
        run: tofu init

      - name: Validate OpenTofu Config  # Step 4: Check syntax
        run: tofu validate

      - name: Run OpenTofu Plan         # Step 5: Plan changes on PR
        if: github.event_name == 'pull_request'
        run: tofu plan

      - name: Run OpenTofu Apply        # Step 6: Auto apply on push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve
