# This GitHub Actions workflow manages the OpenTofu infrastructure lifecycle.
# It validates, plans, and applies changes for both pull requests and direct pushes to main.
name: tofu Plan & Apply  # Name of the workflow

# Define the events that trigger this workflow.
on:
  pull_request:              # Trigger on PRs targeting main
    branches: [ main ]
  push:                      # Trigger on commits pushed to main
    branches: [ main ]

# Set the default working directory for all steps.
defaults:
  run:
    working-directory: ./infra

# Declare the job(s) executed by this workflow.
jobs:
  # Job: Executes OpenTofu operations including plan and apply.
  tofu:                 # Define a job called 'tofu'
    runs-on: ubuntu-latest   # Use latest Ubuntu runner

    # Set environment variables required for AWS and Exoscale access
    env:                     # Define environment variables from GitHub secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
      EXOSCALE_REGION: "at-vie-2"
      TF_VAR_PGDB_PW: ${{ secrets.TF_VAR_PGDB_PW }}
      TF_VAR_CLOUDFLARE_API_TOKEN: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}

    # Sequential steps to prepare the environment and execute OpenTofu commands.
    steps:
      # Step: Checkout the repository code
      - name: Checkout repository  # Step 1: Checkout code
        uses: actions/checkout@v4

      # Step: Install Exoscale CLI for SKS cluster management
      - name: Install Exoscale CLI
        continue-on-error: true
        run: |
          curl -fsSL https://raw.githubusercontent.com/exoscale/cli/master/install-latest.sh | sh

      # Step: Retrieve SKS cluster kubeconfig
      - name: Fetch SKS kubeconfig and store
        continue-on-error: true
        run: |
          CLUSTER_NAME=$(exo compute sks list --zone at-vie-2 --output-format json | jq -r '.[0].name')
          exo compute sks kubeconfig $CLUSTER_NAME admin --zone at-vie-2 > kubeconfig
          chmod 600 kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> $GITHUB_ENV

      # Step: Test cluster connectivity
      - name: Validate Kubernetes access
        continue-on-error: true
        run: |
          kubectl get nodes

      # Step: Install OpenTofu CLI
      - name: Install OpenTofu     # Step 2: Install OpenTofu CLI
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      # Step: Initialize OpenTofu working directory
      - name: Initialize OpenTofu  # Step 3: Initialize the working directory
        run: tofu init # Upgrade the OpenTofu provider plugins

      # Step: Validate configuration syntax
      - name: Validate OpenTofu Config  # Step 4: Check syntax
        run: tofu validate

      # Step: Generate plan preview on PR
      - name: Run OpenTofu Plan         # Step 5: Plan changes on PR
        if: github.event_name == 'pull_request'
        run: tofu plan

      # Step: Apply changes automatically on push to main
      - name: Run OpenTofu Apply        # Step 6: Auto apply on push to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: tofu apply -auto-approve
