name: OpenTofu Apply  # Workflow name shown in GitHub Actions tab

on:
  workflow_dispatch:  # Enables manual execution from the UI
    inputs:
      confirm_apply:                 # Require confirmation input
        description: "Type APPLY to confirm deploying the latest main branch"
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    env:                             # Use required secrets and env vars
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
      EXOSCALE_API_SECRET: ${{ secrets.EXOSCALE_API_SECRET }}
      EXOSCALE_REGION: "at-vie-2"

    steps:
      - name: Check confirmation input      # Block if user didn’t type APPLY
        if: ${{ github.event.inputs.confirm_apply != 'APPLY' }}
        run: |
          echo "❌ Confirmation failed. You must type APPLY to deploy."
          exit 1

      - name: Checkout main branch          # Pull latest infra code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install OpenTofu              # Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.2

      - name: Initialize OpenTofu           # Init working directory
        run: tofu init

      - name: Apply with OpenTofu           # Apply infrastructure
        run: tofu apply -auto-approve
